//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

// #import "UIColor.h"

@interface UIColor (GlobalColors)
+ (id)hexStringFromColor:(id)arg1;
+ (id)cellSeparatorColor;
+ (id)cellSecondaryTextColor;
+ (id)cellPrimaryTextColor;
+ (id)selectedCellBackgroundColor:(_Bool)arg1;
+ (id)selectedCellBackgroundColorDark:(_Bool)arg1 oled:(_Bool)arg2;
+ (id)selectedCellBackgroundColorLight:(_Bool)arg1;
+ (id)cellBackgroundColor;
+ (id)tableViewBackgroundColor;
+ (id)badgeColor;
+ (id)navBarTintColor;
+ (id)tintColor;
@end

